# -*- coding: utf-8 -*-
"""QR_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjEjQrUZGlXGV56Jlw8NIGXd1VugbTcC
"""

#simple
!pip install qrcode
import qrcode
img  =  qrcode.make("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
img.save  ("youtube.png")

import qrcode
from PIL import Image
qr = qrcode.QRCode(version= 1, error_correction= qrcode.constants.ERROR_CORRECT_H, box_size =5 , border =2,)
qr.add_data("https://www.youtube.com/watch?v=I0IbIl4mHwI&list=RDI0IbIl4mHwI&start_radio=1")
qr.make(fit = True)
img = qr.make_image(fill_color = "red", back_color = "blue")
img.save("song.png")

